#!/bin/sh
### BEGIN INIT INFO
# Provides:          checkvol
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Daemon FTP Radar checkVol
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Daemon FTP Radar checkVol"
NAME="checkvol"
DAEMON=/home/muran/Scripts_FTP_Radar/checkVol.sh
PIDFILE=/var/run/$NAME.pid
USER=muran

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Iniciando $DESC" "$NAME"
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $USER --exec $DAEMON
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Parando $DESC" "$NAME"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry TERM/5/KILL/5
    rm -f $PIDFILE
    log_end_msg $?
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Uso: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 3
    ;;
esac
exit 0

